#!/bin/sh

python ${LUMOS_HOME}/lumos/analyses/asicopt_mt.py --kernels=${LUMOS_HOME}/analyses/asicopt/kernels_norm40x10_fixed40_asicfpgaratio50x.xml --series=fixed10_norm40x10_cov10 --workload=${LUMOS_HOME}/analyses/asicopt/workload_fixed10_norm40x10_cov10.xml
python ${LUMOS_HOME}/lumos/analyses/asicopt_mt.py --kernels=${LUMOS_HOME}/analyses/asicopt/kernels_norm40x10_fixed40_asicfpgaratio50x.xml --series=fixed10_norm40x10_cov20 --workload=${LUMOS_HOME}/analyses/asicopt/workload_fixed10_norm40x10_cov20.xml
python ${LUMOS_HOME}/lumos/analyses/asicopt_mt.py --kernels=${LUMOS_HOME}/analyses/asicopt/kernels_norm40x10_fixed40_asicfpgaratio50x.xml --series=fixed10_norm40x10_cov30 --workload=${LUMOS_HOME}/analyses/asicopt/workload_fixed10_norm40x10_cov30.xml
python ${LUMOS_HOME}/lumos/analyses/asicopt_mt.py --kernels=${LUMOS_HOME}/analyses/asicopt/kernels_norm40x10_fixed40_asicfpgaratio50x.xml --series=fixed10_norm40x10_cov40 --workload=${LUMOS_HOME}/analyses/asicopt/workload_fixed10_norm40x10_cov40.xml
python ${LUMOS_HOME}/lumos/analyses/asicopt_mt.py --kernels=${LUMOS_HOME}/analyses/asicopt/kernels_norm40x10_fixed40_asicfpgaratio50x.xml --series=fixed20_norm40x10_cov10 --workload=${LUMOS_HOME}/analyses/asicopt/workload_fixed20_norm40x10_cov10.xml
python ${LUMOS_HOME}/lumos/analyses/asicopt_mt.py --kernels=${LUMOS_HOME}/analyses/asicopt/kernels_norm40x10_fixed40_asicfpgaratio50x.xml --series=fixed20_norm40x10_cov20 --workload=${LUMOS_HOME}/analyses/asicopt/workload_fixed20_norm40x10_cov20.xml
python ${LUMOS_HOME}/lumos/analyses/asicopt_mt.py --kernels=${LUMOS_HOME}/analyses/asicopt/kernels_norm40x10_fixed40_asicfpgaratio50x.xml --series=fixed20_norm40x10_cov30 --workload=${LUMOS_HOME}/analyses/asicopt/workload_fixed20_norm40x10_cov30.xml
python ${LUMOS_HOME}/lumos/analyses/asicopt_mt.py --kernels=${LUMOS_HOME}/analyses/asicopt/kernels_norm40x10_fixed40_asicfpgaratio50x.xml --series=fixed20_norm40x10_cov40 --workload=${LUMOS_HOME}/analyses/asicopt/workload_fixed20_norm40x10_cov40.xml
python ${LUMOS_HOME}/lumos/analyses/asicopt_mt.py --kernels=${LUMOS_HOME}/analyses/asicopt/kernels_norm40x10_fixed40_asicfpgaratio50x.xml --series=fixed30_norm40x10_cov10 --workload=${LUMOS_HOME}/analyses/asicopt/workload_fixed30_norm40x10_cov10.xml
python ${LUMOS_HOME}/lumos/analyses/asicopt_mt.py --kernels=${LUMOS_HOME}/analyses/asicopt/kernels_norm40x10_fixed40_asicfpgaratio50x.xml --series=fixed30_norm40x10_cov20 --workload=${LUMOS_HOME}/analyses/asicopt/workload_fixed30_norm40x10_cov20.xml
python ${LUMOS_HOME}/lumos/analyses/asicopt_mt.py --kernels=${LUMOS_HOME}/analyses/asicopt/kernels_norm40x10_fixed40_asicfpgaratio50x.xml --series=fixed30_norm40x10_cov30 --workload=${LUMOS_HOME}/analyses/asicopt/workload_fixed30_norm40x10_cov30.xml
python ${LUMOS_HOME}/lumos/analyses/asicopt_mt.py --kernels=${LUMOS_HOME}/analyses/asicopt/kernels_norm40x10_fixed40_asicfpgaratio50x.xml --series=fixed30_norm40x10_cov40 --workload=${LUMOS_HOME}/analyses/asicopt/workload_fixed30_norm40x10_cov40.xml
python ${LUMOS_HOME}/lumos/analyses/asicopt_mt.py --kernels=${LUMOS_HOME}/analyses/asicopt/kernels_norm40x10_fixed40_asicfpgaratio50x.xml --series=fixed40_norm40x10_cov10 --workload=${LUMOS_HOME}/analyses/asicopt/workload_fixed40_norm40x10_cov10.xml
python ${LUMOS_HOME}/lumos/analyses/asicopt_mt.py --kernels=${LUMOS_HOME}/analyses/asicopt/kernels_norm40x10_fixed40_asicfpgaratio50x.xml --series=fixed40_norm40x10_cov20 --workload=${LUMOS_HOME}/analyses/asicopt/workload_fixed40_norm40x10_cov20.xml
python ${LUMOS_HOME}/lumos/analyses/asicopt_mt.py --kernels=${LUMOS_HOME}/analyses/asicopt/kernels_norm40x10_fixed40_asicfpgaratio50x.xml --series=fixed40_norm40x10_cov30 --workload=${LUMOS_HOME}/analyses/asicopt/workload_fixed40_norm40x10_cov30.xml
python ${LUMOS_HOME}/lumos/analyses/asicopt_mt.py --kernels=${LUMOS_HOME}/analyses/asicopt/kernels_norm40x10_fixed40_asicfpgaratio50x.xml --series=fixed40_norm40x10_cov40 --workload=${LUMOS_HOME}/analyses/asicopt/workload_fixed40_norm40x10_cov40.xml
