# Batching script for generating data
#
# 01_fpga40x_varcov
python lumos/analyses/fpgainc_mt.py --ucore-ratio=10 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_asic_inc.xml --series=01_fpga40x_varcov
python lumos/analyses/fpgainc_mt.py --ucore-ratio=15 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_asic_inc.xml --series=01_fpga40x_varcov
python lumos/analyses/fpgainc_mt.py --ucore-ratio=20 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_asic_inc.xml --series=01_fpga40x_varcov
python lumos/analyses/fpgainc_mt.py --ucore-ratio=25 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_asic_inc.xml --series=01_fpga40x_varcov
python lumos/analyses/fpgainc_mt.py --ucore-ratio=30 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_asic_inc.xml --series=01_fpga40x_varcov
python lumos/analyses/fpgainc_mt.py --ucore-ratio=35 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_asic_inc.xml --series=01_fpga40x_varcov
python lumos/analyses/fpgainc_mt.py --ucore-ratio=40 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_asic_inc.xml --series=01_fpga40x_varcov
python lumos/analyses/fpgainc_mt.py --ucore-ratio=45 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_asic_inc.xml --series=01_fpga40x_varcov
python lumos/analyses/fpgainc_mt.py --ucore-ratio=50 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_asic_inc.xml --series=01_fpga40x_varcov
python lumos/analyses/fpgainc_mt.py --ucore-ratio=55 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_asic_inc.xml --series=01_fpga40x_varcov
python lumos/analyses/fpgainc_mt.py --ucore-ratio=60 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_asic_inc.xml --series=01_fpga40x_varcov
python lumos/analyses/fpgainc_mt.py --ucore-ratio=65 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_asic_inc.xml --series=01_fpga40x_varcov
python lumos/analyses/fpgainc_mt.py --ucore-ratio=70 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_asic_inc.xml --series=01_fpga40x_varcov
python lumos/analyses/fpgainc_mt.py --ucore-ratio=75 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_asic_inc.xml --series=01_fpga40x_varcov
python lumos/analyses/fpgainc_mt.py --ucore-ratio=80 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_asic_inc.xml --series=01_fpga40x_varcov
python lumos/analyses/fpgainc_mt.py --ucore-ratio=85 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_asic_inc.xml --series=01_fpga40x_varcov
# 02_fpga40x_cov30
python lumos/analyses/fpgainc_mt.py --ucore-ratio=10 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov30.xml --series=02_fpga40x_cov30
python lumos/analyses/fpgainc_mt.py --ucore-ratio=15 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov30.xml --series=02_fpga40x_cov30
python lumos/analyses/fpgainc_mt.py --ucore-ratio=20 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov30.xml --series=02_fpga40x_cov30
python lumos/analyses/fpgainc_mt.py --ucore-ratio=25 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov30.xml --series=02_fpga40x_cov30
python lumos/analyses/fpgainc_mt.py --ucore-ratio=30 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov30.xml --series=02_fpga40x_cov30
python lumos/analyses/fpgainc_mt.py --ucore-ratio=35 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov30.xml --series=02_fpga40x_cov30
python lumos/analyses/fpgainc_mt.py --ucore-ratio=40 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov30.xml --series=02_fpga40x_cov30
python lumos/analyses/fpgainc_mt.py --ucore-ratio=45 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov30.xml --series=02_fpga40x_cov30
python lumos/analyses/fpgainc_mt.py --ucore-ratio=50 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov30.xml --series=02_fpga40x_cov30
python lumos/analyses/fpgainc_mt.py --ucore-ratio=55 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov30.xml --series=02_fpga40x_cov30
python lumos/analyses/fpgainc_mt.py --ucore-ratio=60 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov30.xml --series=02_fpga40x_cov30
python lumos/analyses/fpgainc_mt.py --ucore-ratio=65 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov30.xml --series=02_fpga40x_cov30
python lumos/analyses/fpgainc_mt.py --ucore-ratio=70 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov30.xml --series=02_fpga40x_cov30
python lumos/analyses/fpgainc_mt.py --ucore-ratio=75 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov30.xml --series=02_fpga40x_cov30
python lumos/analyses/fpgainc_mt.py --ucore-ratio=80 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov30.xml --series=02_fpga40x_cov30
python lumos/analyses/fpgainc_mt.py --ucore-ratio=85 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov30.xml --series=02_fpga40x_cov30
# 03_fpga40x_cov50
python lumos/analyses/fpgainc_mt.py --ucore-ratio=10 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov50.xml --series=03_fpga40x_cov50 
python lumos/analyses/fpgainc_mt.py --ucore-ratio=15 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov50.xml --series=03_fpga40x_cov50
python lumos/analyses/fpgainc_mt.py --ucore-ratio=20 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov50.xml --series=03_fpga40x_cov50
python lumos/analyses/fpgainc_mt.py --ucore-ratio=25 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov50.xml --series=03_fpga40x_cov50
python lumos/analyses/fpgainc_mt.py --ucore-ratio=30 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov50.xml --series=03_fpga40x_cov50
python lumos/analyses/fpgainc_mt.py --ucore-ratio=35 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov50.xml --series=03_fpga40x_cov50
python lumos/analyses/fpgainc_mt.py --ucore-ratio=40 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov50.xml --series=03_fpga40x_cov50
python lumos/analyses/fpgainc_mt.py --ucore-ratio=45 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov50.xml --series=03_fpga40x_cov50
python lumos/analyses/fpgainc_mt.py --ucore-ratio=50 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov50.xml --series=03_fpga40x_cov50 
python lumos/analyses/fpgainc_mt.py --ucore-ratio=55 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov50.xml --series=03_fpga40x_cov50
python lumos/analyses/fpgainc_mt.py --ucore-ratio=60 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov50.xml --series=03_fpga40x_cov50
python lumos/analyses/fpgainc_mt.py --ucore-ratio=65 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov50.xml --series=03_fpga40x_cov50
python lumos/analyses/fpgainc_mt.py --ucore-ratio=70 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov50.xml --series=03_fpga40x_cov50
python lumos/analyses/fpgainc_mt.py --ucore-ratio=75 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov50.xml --series=03_fpga40x_cov50
python lumos/analyses/fpgainc_mt.py --ucore-ratio=80 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov50.xml --series=03_fpga40x_cov50
python lumos/analyses/fpgainc_mt.py --ucore-ratio=85 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov50.xml --series=03_fpga40x_cov50
# 04_fpga40x_cov70
python lumos/analyses/fpgainc_mt.py --ucore-ratio=10 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov70.xml --series=04_fpga40x_cov70 
python lumos/analyses/fpgainc_mt.py --ucore-ratio=15 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov70.xml --series=04_fpga40x_cov70
python lumos/analyses/fpgainc_mt.py --ucore-ratio=20 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov70.xml --series=04_fpga40x_cov70
python lumos/analyses/fpgainc_mt.py --ucore-ratio=25 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov70.xml --series=04_fpga40x_cov70
python lumos/analyses/fpgainc_mt.py --ucore-ratio=30 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov70.xml --series=04_fpga40x_cov70
python lumos/analyses/fpgainc_mt.py --ucore-ratio=35 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov70.xml --series=04_fpga40x_cov70
python lumos/analyses/fpgainc_mt.py --ucore-ratio=40 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov70.xml --series=04_fpga40x_cov70
python lumos/analyses/fpgainc_mt.py --ucore-ratio=45 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov70.xml --series=04_fpga40x_cov70
python lumos/analyses/fpgainc_mt.py --ucore-ratio=50 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov70.xml --series=04_fpga40x_cov70 
python lumos/analyses/fpgainc_mt.py --ucore-ratio=55 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov70.xml --series=04_fpga40x_cov70
python lumos/analyses/fpgainc_mt.py --ucore-ratio=60 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov70.xml --series=04_fpga40x_cov70
python lumos/analyses/fpgainc_mt.py --ucore-ratio=65 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov70.xml --series=04_fpga40x_cov70
python lumos/analyses/fpgainc_mt.py --ucore-ratio=70 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov70.xml --series=04_fpga40x_cov70
python lumos/analyses/fpgainc_mt.py --ucore-ratio=75 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov70.xml --series=04_fpga40x_cov70
python lumos/analyses/fpgainc_mt.py --ucore-ratio=80 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov70.xml --series=04_fpga40x_cov70
python lumos/analyses/fpgainc_mt.py --ucore-ratio=85 --kernels=data/kernels/kernels_asic_inc.xml --workload=data/workloads/workload_fpga40x_cov70.xml --series=04_fpga40x_cov70
# 05_fpga80x_varcov
python lumos/analyses/fpgainc_mt.py --ucore-ratio=10 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_varcov.xml --series=05_fpga80x_varcov 
python lumos/analyses/fpgainc_mt.py --ucore-ratio=15 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_varcov.xml --series=05_fpga80x_varcov
python lumos/analyses/fpgainc_mt.py --ucore-ratio=20 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_varcov.xml --series=05_fpga80x_varcov
python lumos/analyses/fpgainc_mt.py --ucore-ratio=25 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_varcov.xml --series=05_fpga80x_varcov
python lumos/analyses/fpgainc_mt.py --ucore-ratio=30 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_varcov.xml --series=05_fpga80x_varcov
python lumos/analyses/fpgainc_mt.py --ucore-ratio=35 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_varcov.xml --series=05_fpga80x_varcov
python lumos/analyses/fpgainc_mt.py --ucore-ratio=40 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_varcov.xml --series=05_fpga80x_varcov
python lumos/analyses/fpgainc_mt.py --ucore-ratio=45 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_varcov.xml --series=05_fpga80x_varcov
python lumos/analyses/fpgainc_mt.py --ucore-ratio=50 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_varcov.xml --series=05_fpga80x_varcov 
python lumos/analyses/fpgainc_mt.py --ucore-ratio=55 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_varcov.xml --series=05_fpga80x_varcov
python lumos/analyses/fpgainc_mt.py --ucore-ratio=60 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_varcov.xml --series=05_fpga80x_varcov
python lumos/analyses/fpgainc_mt.py --ucore-ratio=65 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_varcov.xml --series=05_fpga80x_varcov
python lumos/analyses/fpgainc_mt.py --ucore-ratio=70 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_varcov.xml --series=05_fpga80x_varcov
python lumos/analyses/fpgainc_mt.py --ucore-ratio=75 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_varcov.xml --series=05_fpga80x_varcov
python lumos/analyses/fpgainc_mt.py --ucore-ratio=80 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_varcov.xml --series=05_fpga80x_varcov
python lumos/analyses/fpgainc_mt.py --ucore-ratio=85 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_varcov.xml --series=05_fpga80x_varcov
# 06_fpga80x_cov30
python lumos/analyses/fpgainc_mt.py --ucore-ratio=10 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov30.xml --series=06_fpga80x_cov30 
python lumos/analyses/fpgainc_mt.py --ucore-ratio=15 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov30.xml --series=06_fpga80x_cov30
python lumos/analyses/fpgainc_mt.py --ucore-ratio=20 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov30.xml --series=06_fpga80x_cov30
python lumos/analyses/fpgainc_mt.py --ucore-ratio=25 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov30.xml --series=06_fpga80x_cov30
python lumos/analyses/fpgainc_mt.py --ucore-ratio=30 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov30.xml --series=06_fpga80x_cov30
python lumos/analyses/fpgainc_mt.py --ucore-ratio=35 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov30.xml --series=06_fpga80x_cov30
python lumos/analyses/fpgainc_mt.py --ucore-ratio=40 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov30.xml --series=06_fpga80x_cov30
python lumos/analyses/fpgainc_mt.py --ucore-ratio=45 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov30.xml --series=06_fpga80x_cov30
python lumos/analyses/fpgainc_mt.py --ucore-ratio=50 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov30.xml --series=06_fpga80x_cov30 
python lumos/analyses/fpgainc_mt.py --ucore-ratio=55 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov30.xml --series=06_fpga80x_cov30
python lumos/analyses/fpgainc_mt.py --ucore-ratio=60 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov30.xml --series=06_fpga80x_cov30
python lumos/analyses/fpgainc_mt.py --ucore-ratio=65 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov30.xml --series=06_fpga80x_cov30
python lumos/analyses/fpgainc_mt.py --ucore-ratio=70 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov30.xml --series=06_fpga80x_cov30
python lumos/analyses/fpgainc_mt.py --ucore-ratio=75 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov30.xml --series=06_fpga80x_cov30
python lumos/analyses/fpgainc_mt.py --ucore-ratio=80 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov30.xml --series=06_fpga80x_cov30
python lumos/analyses/fpgainc_mt.py --ucore-ratio=85 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov30.xml --series=06_fpga80x_cov30
# 07_fpga80x_cov50
python lumos/analyses/fpgainc_mt.py --ucore-ratio=10 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov50.xml --series=07_fpga80x_cov50 
python lumos/analyses/fpgainc_mt.py --ucore-ratio=15 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov50.xml --series=07_fpga80x_cov50
python lumos/analyses/fpgainc_mt.py --ucore-ratio=20 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov50.xml --series=07_fpga80x_cov50
python lumos/analyses/fpgainc_mt.py --ucore-ratio=25 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov50.xml --series=07_fpga80x_cov50
python lumos/analyses/fpgainc_mt.py --ucore-ratio=30 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov50.xml --series=07_fpga80x_cov50
python lumos/analyses/fpgainc_mt.py --ucore-ratio=35 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov50.xml --series=07_fpga80x_cov50
python lumos/analyses/fpgainc_mt.py --ucore-ratio=40 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov50.xml --series=07_fpga80x_cov50
python lumos/analyses/fpgainc_mt.py --ucore-ratio=45 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov50.xml --series=07_fpga80x_cov50
python lumos/analyses/fpgainc_mt.py --ucore-ratio=50 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov50.xml --series=07_fpga80x_cov50 
python lumos/analyses/fpgainc_mt.py --ucore-ratio=55 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov50.xml --series=07_fpga80x_cov50
python lumos/analyses/fpgainc_mt.py --ucore-ratio=60 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov50.xml --series=07_fpga80x_cov50
python lumos/analyses/fpgainc_mt.py --ucore-ratio=65 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov50.xml --series=07_fpga80x_cov50
python lumos/analyses/fpgainc_mt.py --ucore-ratio=70 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov50.xml --series=07_fpga80x_cov50
python lumos/analyses/fpgainc_mt.py --ucore-ratio=75 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov50.xml --series=07_fpga80x_cov50
python lumos/analyses/fpgainc_mt.py --ucore-ratio=80 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov50.xml --series=07_fpga80x_cov50
python lumos/analyses/fpgainc_mt.py --ucore-ratio=85 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov50.xml --series=07_fpga80x_cov50
# 08_fpga80x_cov70
python lumos/analyses/fpgainc_mt.py --ucore-ratio=10 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov70.xml --series=08_fpga80x_cov70
python lumos/analyses/fpgainc_mt.py --ucore-ratio=15 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov70.xml --series=08_fpga80x_cov70
python lumos/analyses/fpgainc_mt.py --ucore-ratio=20 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov70.xml --series=08_fpga80x_cov70
python lumos/analyses/fpgainc_mt.py --ucore-ratio=25 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov70.xml --series=08_fpga80x_cov70
python lumos/analyses/fpgainc_mt.py --ucore-ratio=30 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov70.xml --series=08_fpga80x_cov70
python lumos/analyses/fpgainc_mt.py --ucore-ratio=35 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov70.xml --series=08_fpga80x_cov70
python lumos/analyses/fpgainc_mt.py --ucore-ratio=40 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov70.xml --series=08_fpga80x_cov70
python lumos/analyses/fpgainc_mt.py --ucore-ratio=45 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov70.xml --series=08_fpga80x_cov70
python lumos/analyses/fpgainc_mt.py --ucore-ratio=50 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov70.xml --series=08_fpga80x_cov70
python lumos/analyses/fpgainc_mt.py --ucore-ratio=55 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov70.xml --series=08_fpga80x_cov70
python lumos/analyses/fpgainc_mt.py --ucore-ratio=60 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov70.xml --series=08_fpga80x_cov70
python lumos/analyses/fpgainc_mt.py --ucore-ratio=65 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov70.xml --series=08_fpga80x_cov70
python lumos/analyses/fpgainc_mt.py --ucore-ratio=70 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov70.xml --series=08_fpga80x_cov70
python lumos/analyses/fpgainc_mt.py --ucore-ratio=75 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov70.xml --series=08_fpga80x_cov70
python lumos/analyses/fpgainc_mt.py --ucore-ratio=80 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov70.xml --series=08_fpga80x_cov70
python lumos/analyses/fpgainc_mt.py --ucore-ratio=85 --kernels=data/kernels/kernels_asic_inc_fpga80x.xml --workload=data/workloads/workload_fpga80x_cov70.xml --series=08_fpga80x_cov70

# 09_multiamdahl
python lumos/analyses/fpgainc_mt.py --ucore-ratio=10 --kernels=data/kernels/kernels_multiamdahl.xml --workload=data/workloads/workload_multiamdahl.xml --series=09_multiamdahl
python lumos/analyses/fpgainc_mt.py --ucore-ratio=15 --kernels=data/kernels/kernels_multiamdahl.xml --workload=data/workloads/workload_multiamdahl.xml --series=09_multiamdahl
python lumos/analyses/fpgainc_mt.py --ucore-ratio=20 --kernels=data/kernels/kernels_multiamdahl.xml --workload=data/workloads/workload_multiamdahl.xml --series=09_multiamdahl
python lumos/analyses/fpgainc_mt.py --ucore-ratio=25 --kernels=data/kernels/kernels_multiamdahl.xml --workload=data/workloads/workload_multiamdahl.xml --series=09_multiamdahl
python lumos/analyses/fpgainc_mt.py --ucore-ratio=30 --kernels=data/kernels/kernels_multiamdahl.xml --workload=data/workloads/workload_multiamdahl.xml --series=09_multiamdahl
python lumos/analyses/fpgainc_mt.py --ucore-ratio=35 --kernels=data/kernels/kernels_multiamdahl.xml --workload=data/workloads/workload_multiamdahl.xml --series=09_multiamdahl
python lumos/analyses/fpgainc_mt.py --ucore-ratio=40 --kernels=data/kernels/kernels_multiamdahl.xml --workload=data/workloads/workload_multiamdahl.xml --series=09_multiamdahl
python lumos/analyses/fpgainc_mt.py --ucore-ratio=45 --kernels=data/kernels/kernels_multiamdahl.xml --workload=data/workloads/workload_multiamdahl.xml --series=09_multiamdahl
python lumos/analyses/fpgainc_mt.py --ucore-ratio=50 --kernels=data/kernels/kernels_multiamdahl.xml --workload=data/workloads/workload_multiamdahl.xml --series=09_multiamdahl
python lumos/analyses/fpgainc_mt.py --ucore-ratio=55 --kernels=data/kernels/kernels_multiamdahl.xml --workload=data/workloads/workload_multiamdahl.xml --series=09_multiamdahl
python lumos/analyses/fpgainc_mt.py --ucore-ratio=60 --kernels=data/kernels/kernels_multiamdahl.xml --workload=data/workloads/workload_multiamdahl.xml --series=09_multiamdahl
python lumos/analyses/fpgainc_mt.py --ucore-ratio=65 --kernels=data/kernels/kernels_multiamdahl.xml --workload=data/workloads/workload_multiamdahl.xml --series=09_multiamdahl
python lumos/analyses/fpgainc_mt.py --ucore-ratio=70 --kernels=data/kernels/kernels_multiamdahl.xml --workload=data/workloads/workload_multiamdahl.xml --series=09_multiamdahl
python lumos/analyses/fpgainc_mt.py --ucore-ratio=75 --kernels=data/kernels/kernels_multiamdahl.xml --workload=data/workloads/workload_multiamdahl.xml --series=09_multiamdahl
python lumos/analyses/fpgainc_mt.py --ucore-ratio=80 --kernels=data/kernels/kernels_multiamdahl.xml --workload=data/workloads/workload_multiamdahl.xml --series=09_multiamdahl
python lumos/analyses/fpgainc_mt.py --ucore-ratio=85 --kernels=data/kernels/kernels_multiamdahl.xml --workload=data/workloads/workload_multiamdahl.xml --series=09_multiamdahl
