python analyses/ucore.py --fmt=png --mode=ap --sec=type --app=MMM --fratio=1,9,90
python analyses/ucore.py --fmt=png --mode=ap --sec=type --app=MMM --fratio=1,90,9
python analyses/ucore.py --fmt=png --mode=ap --sec=type --app=MMM --fratio=1,49,50
python analyses/ucore.py --fmt=png --mode=ap --sec=type --app=MMM --fratio=0,10,90
python analyses/ucore.py --fmt=png --mode=ap --sec=type --app=MMM --fratio=0,90,10
python analyses/ucore.py --fmt=png --mode=ap --sec=type --app=MMM --fratio=0,50,50
python analyses/ucore.py --fmt=png --mode=ap --sec=type --app=BS --fratio=1,9,90
python analyses/ucore.py --fmt=png --mode=ap --sec=type --app=BS --fratio=1,90,9
python analyses/ucore.py --fmt=png --mode=ap --sec=type --app=BS --fratio=1,49,50
python analyses/ucore.py --fmt=png --mode=ap --sec=type --app=BS --fratio=0,10,90
python analyses/ucore.py --fmt=png --mode=ap --sec=type --app=BS --fratio=0,90,10
python analyses/ucore.py --fmt=png --mode=ap --sec=type --app=BS --fratio=0,50,50
